#!/bin/sh
set -e

export OLD_GOPATH=$GOPATH

NEW_GOPATH=$(mktemp -d)
[[ -e "vendor.tar" ]] && tar -xf vendor.tar -C "$NEW_GOPATH"
export GOPATH="$NEW_GOPATH:$GOPATH"

function cleanup {
    set +e
    tar -cf vendor.tar -C "$NEW_GOPATH" .
    rm -fr "$NEW_GOPATH"
}
trap "cleanup" EXIT

(set +e; goimp get)
if [ -z "$PS1" ]; then
    export PS1="[go] $(basename $(pwd))=> "
else
    export PS1="[go] $PS1"
fi
$SHELL

